import csv
import json
from pathlib import Path
from typing import List, Dict, Any

import click

BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data" / "real_reviews"
DATA_DIR.mkdir(parents=True, exist_ok=True)
DEFAULT_OUT = DATA_DIR / "reviews.jsonl"


def _write_jsonl(rows: List[Dict[str, Any]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("a", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def _normalize_row(source: str, raw: Dict[str, str]) -> Dict[str, Any]:
    """Normalize a row into the schema expected by the pipeline."""
    return {
        "source": source,
        "platform": raw.get("platform") or source,
        "review_id": raw.get("id") or raw.get("review_id"),
        "title": raw.get("title") or "",
        "body": raw.get("body") or raw.get("review_text") or "",
        "rating": float(raw.get("rating", 0) or 0),
        "author": raw.get("author") or raw.get("user") or "",
        "product": raw.get("product") or raw.get("tool") or "",
        "url": raw.get("url") or "",
        "metadata": {
            k: v
            for k, v in raw.items()
            if k
            not in {
                "id",
                "review_id",
                "title",
                "body",
                "review_text",
                "rating",
                "author",
                "user",
                "product",
                "tool",
                "url",
                "platform",
            }
        },
    }


@click.group()
def cli() -> None:
    """Collect and normalize real reviews into data/real_reviews/reviews.jsonl."""


@cli.command("from-csv")
@click.argument("csv_path", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option(
    "--source",
    default="csv",
    help="Logical source label (e.g. g2, capterra, reddit).",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_OUT,
    show_default=True,
)
def from_csv(csv_path: Path, source: str, output: Path) -> None:
    """Ingest reviews from a CSV file generated by your own pipeline/templates."""
    rows: List[Dict[str, Any]] = []
    with csv_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for raw in reader:
            rows.append(_normalize_row(source, raw))

    _write_jsonl(rows, output)
    click.echo(f"✓ Appended {len(rows)} reviews from {csv_path} to {output}")


@cli.command("interactive")
@click.option(
    "--output",
    "-o",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_OUT,
    show_default=True,
)
def interactive(output: Path) -> None:
    """Interactive helper to manually enter a few seed reviews."""
    click.echo("Interactive real-review capture. Press ENTER on title to stop.")
    rows: List[Dict[str, Any]] = []
    while True:
        title = click.prompt("Title (blank to finish)", default="", show_default=False)
        if not title.strip():
            break
        body = click.prompt("Body", default="", show_default=False)
        rating = click.prompt("Rating 1–5", type=float, default=5.0)
        product = click.prompt("Product / tool", default="", show_default=False)
        platform = click.prompt("Platform (g2/capterra/reddit/etc.)", default="manual")

        rows.append(
            {
                "title": title,
                "body": body,
                "rating": rating,
                "product": product,
                "platform": platform,
            }
        )

    if not rows:
        click.echo("No reviews entered, nothing written.")
        return

    _write_jsonl([_normalize_row("manual", r) for r in rows], output)
    click.echo(f"✓ Appended {len(rows)} reviews to {output}")


if __name__ == "__main__":
    cli()
